# Generated by Django 6.0.2 on 2026-03-03 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_autor_post_usuario_remove_post_total_curtidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
